root: true
parser: "@typescript-eslint/parser"
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:svelte/recommended
    - plugin:svelte/prettier
    - plugin:@typescript-eslint/recommended-requiring-type-checking
plugins:
    - "@typescript-eslint"
env:
    es2022: true
    browser: true
    node: true
parserOptions:
    sourceType: "module"
    ecmaVersion: latest
    extraFileExtensions:
        - ".svelte"
    tsconfigRootDir: __dirname,
    project:
        - "./tsconfig.json"
overrides:
    - files:
          - "*.svelte"
      parser: svelte-eslint-parser
      parserOptions:
          parser: "@typescript-eslint/parser"
rules:
    "@typescript-eslint/no-empty-function": off
    "@typescript-eslint/no-unused-vars":
        - warn
        - {
              varsIgnorePattern: ^_,
              argsIgnorePattern: ^_,
              destructuredArrayIgnorePattern: ^_,
          }
